import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import { Collection } from "../typings";
import { sanityClient, urlFor } from "../sanity";
import Link from "next/link";

interface Props {
  collections: Collection[];
}

const Home = ({ collections }: Props) => {
  return (
    <div className="flex mx-auto max-w-7xl flex-col min-h-screen py-20 px-10 2xl:px-0">
      <Head>
        <title>NFT DROP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={"/"}>
        <h1 className="mb-10 text-4xl font-extralight">
          The{" "}
          <span className="font-extrabold underline decoration-pink-600/50">
            PAPAFAM
          </span>{" "}
          NFT Marketplace
        </h1>
      </Link>
      <main className="bg-slate-100 shadow-xl shadow-rose-400/20 p-10">
        <div className="grid space-x-3 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
          {collections.map((collection) => (
            <Link href={`/nft/${collection.slug.current}`}>
              <div className="flex flex-col items-center cursor-pointer transition-all duration-200 hover:scale-105">
                <img
                  className="h-96 w-60 rounded-2xl object-cover"
                  src={urlFor(collection.mainImage).url()}
                  alt=""
                />

                <div className="p-5">
                  <h2 className="text-3xl">{collection.title}</h2>
                  <p className="mt-2 text-sm text-gray-400">
                    {collection.description}
                  </p>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection"]{
    _id,
    title,
    address,
    description,
    nftCollectionName,
    mainImage {
      asset
    },
    slug {
      current
    },
    creator-> {
      _id,
      name,
      address,
      slug{
        current
      },
    },
  }`;

  const collections = await sanityClient.fetch(query);

  return {
    props: {
      collections,
    },
  };
};
